# Generated by Django 4.2.11 on 2024-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
