# Generated by Django 4.2.11 on 2024-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_transaction_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
