# Generated by Django 4.2.11 on 2024-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_rename_percent_sum_portfolio_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
