# Generated by Django 4.2.11 on 2024-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_portfolioitem_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
