# Generated by Django 4.2.11 on 2024-03-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_app', '0007_portfolioitem_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('chatid', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False, help_text='активирован')),
                ('active_code', models.CharField(blank=True, help_text='код активации', max_length=200, null=True)),
                ('updata_active_code', models.BooleanField(default=False, help_text='обновить код активации')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio')),
            ],
        ),
    ]
