# Generated by Django 4.2.11 on 2024-03-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletg',
            name='chatid',
            field=models.PositiveIntegerField(blank=True, help_text='id чата', null=True),
        ),
    ]
