# Generated by Django 4.2.11 on 2024-03-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_alter_profiletg_chatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletg',
            name='chatid',
            field=models.PositiveIntegerField(default=0, help_text='id чата'),
        ),
    ]
