# Generated by Django 4.2.11 on 2024-03-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_portfolio_balance'),
        ('tg_bot', '0003_alter_profiletg_chatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletg',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgbots', to='portfolio_app.portfolio'),
        ),
    ]
